hs.urlevent.bind("idea", function(eventName, params)
    applyLayouts(layout.idea)
end)
hs.urlevent.bind("chat", function(eventName, params)
    applyLayouts(layout.chat)
end)
hs.urlevent.bind("vscode", function(eventName, params)
    applyLayouts(layout.vscode)
end)